import type { Generated, ColumnType } from "kysely";

interface PostTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>;
  title: string;
  description: string;
  body: string;
  taglist: string[];
  image: string | null;

  // You can specify a different type for each operation (select, insert and
  // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
  // wrapper. Here we define a column `modified_at` that is selected as
  // a `Date`, can optionally be provided as a `string` in inserts and
  // can never be updated:
  modified_at: ColumnType<Date, string | undefined, never>;
  created_at: ColumnType<Date, string | undefined, never>;
}

export type Post = Omit<PostTable, "id" | "modified_at" | "created_at">;

// Keys of this interface are table names.
export interface Database {
  post_psycho: PostTable;
}
